# Generated by Django 5.1.7 on 2025-03-31 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cpnj", models.CharField(max_length=18)),
                ("telefone", models.CharField(max_length=15)),
                ("endereco", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("especie", models.CharField(max_length=50)),
                ("raca", models.CharField(max_length=50)),
                ("idade", models.PositiveSmallIntegerField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Macho"), ("F", "Fêmea")], max_length=1
                    ),
                ),
                ("descricao", models.TextField()),
                ("foto", models.ImageField(upload_to="animais/")),
                ("disponivel", models.BooleanField(default=True)),
                (
                    "ong",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Miaudota.ong"
                    ),
                ),
            ],
        ),
    ]
