# Generated by Django 5.1.7 on 2025-06-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miaudota', '0002_adotante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adotante',
            name='consentimento',
        ),
        migrations.RemoveField(
            model_name='adotante',
            name='email',
        ),
        migrations.AlterField(
            model_name='adotante',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
